# This file mirrors what GoReleaser writes on release. Regenerated by a release run once
# HOMEBREW_TAP_TOKEN is set on DawnBreather/tmux-hub; written by hand for v0.1.1.
cask "tmux-hub" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "4c9418b8abc2c35d3c8d04f84cc219c7f67bc8aabfc458354ccfafb9264e1908"
      url "https://github.com/DawnBreather/tmux-hub/releases/download/v#{version}/tmux-hub_#{version}_macos_amd64.tar.gz"
    end
    on_arm do
      sha256 "9bc7b09728a00067ff8f0a01136713ab90a465362d9e0e347018a52a64dbeb8b"
      url "https://github.com/DawnBreather/tmux-hub/releases/download/v#{version}/tmux-hub_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "51abcacf6d43de923ebf4b0b2069cddeaa1a2d86ee4026fbffbd6c140098713d"
      url "https://github.com/DawnBreather/tmux-hub/releases/download/v#{version}/tmux-hub_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd4b37a8611570aabf26d88dbabec535321eb4f0aec5c337f75fe319a254ed7f"
      url "https://github.com/DawnBreather/tmux-hub/releases/download/v#{version}/tmux-hub_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tmux-hub"
  desc "A control panel over local and remote tmux servers, built for many Claude Code sessions at once"
  homepage "https://github.com/DawnBreather/tmux-hub"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "tmux-hub"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/tmux-hub"]
    end
  end
end
