# This file mirrors what GoReleaser writes on release. Regenerated by a release run once
# HOMEBREW_TAP_TOKEN is set on DawnBreather/tmux-hub; written by hand for v0.2.1 (the token is still unset,
# so the release run took its --skip=homebrew branch).
cask "tmux-hub" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "8db34c90e547863bf3b692ae000da9a66315d24cebe2ad1a5cc21f5c1ed9d0c1"
      url "https://github.com/DawnBreather/tmux-hub/releases/download/v#{version}/tmux-hub_#{version}_macos_amd64.tar.gz"
    end
    on_arm do
      sha256 "5e3dadd6e5a1ac0a7fdd4bfd398dce2929fbe9a8803b4c2407b7461b35051f46"
      url "https://github.com/DawnBreather/tmux-hub/releases/download/v#{version}/tmux-hub_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0d1870e0a295c5ece571ce63f3239af2b3e4bb1d3d2aa8a7bc69a15b7e07d625"
      url "https://github.com/DawnBreather/tmux-hub/releases/download/v#{version}/tmux-hub_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9ca1781500fe8a909a84c7f060b601bae9b3813d271582f54dad8e604327c905"
      url "https://github.com/DawnBreather/tmux-hub/releases/download/v#{version}/tmux-hub_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tmux-hub"
  desc "A control panel over local and remote tmux servers, built for many Claude Code sessions at once"
  homepage "https://github.com/DawnBreather/tmux-hub"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "tmux-hub"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/tmux-hub"]
    end
  end
end
