# This file mirrors what GoReleaser writes on release. Regenerated by a release run once
# HOMEBREW_TAP_TOKEN is set on DawnBreather/tmux-hub; written by hand for v0.1.0.
cask "tmux-hub" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "10bee809e6b5c11b1cd1b3a77132f718cf565bb152c3becda273745af327c349"
      url "https://github.com/DawnBreather/tmux-hub/releases/download/v#{version}/tmux-hub_#{version}_macos_amd64.tar.gz"
    end
    on_arm do
      sha256 "96dbfaea243aeaf90b3c7c00599b46e74424633a02a91678e93b196410a5ffc8"
      url "https://github.com/DawnBreather/tmux-hub/releases/download/v#{version}/tmux-hub_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec0165fa6dda0bd439fa2a041dffcbc14328be9ff6c04c5c7c4575e10785a728"
      url "https://github.com/DawnBreather/tmux-hub/releases/download/v#{version}/tmux-hub_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "393131ef5b206bbcdf0ac3f5a3c024de7dc8a64e969d80c6f1ece446c8a484f0"
      url "https://github.com/DawnBreather/tmux-hub/releases/download/v#{version}/tmux-hub_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tmux-hub"
  desc "A control panel over local and remote tmux servers, built for many Claude Code sessions at once"
  homepage "https://github.com/DawnBreather/tmux-hub"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "tmux-hub"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/tmux-hub"]
    end
  end
end
